### ISSUE TITLE
get_meta_subset function not found

### ISSUE THREAD

**Issue by DOH-FAA3303** [atorus-research/Tplyr-shiny-demo#1]
Hello,

I tried to follow this code and run it myself but there are a few things that don't appear to be included in the Tplyr package like -

- `get_meta_subset()` 
- `append_metadata()`
- `tplyr_meta()`
- and in the `build` function the `metadata` option does not exist. 

Are these only available in the dev version?

**Comment by mstackhouse** [comment]
Hi @DOH-FAA3303 yes these are actually making their way into dev now in a set of other updates that we're planning for hte next major version release. 

You can install with devtools::install_github("https://github.com/atorus-research/Tplyr.git", ref="gh_issue_32")

**Comment by DOH-FAA3303** [comment]
> Hi @DOH-FAA3303 yes these are actually making their way into dev now in a set of other updates that we're planning for hte next major version release.
> 
> You can install with devtools::install_github("https://github.com/atorus-research/Tplyr.git", ref="gh_issue_32")

Awesome, thank you! This is a really cool package btw!
